language: java
sudo: false

branches:
  only:
    - stable
    - master

Env:

jdk:

matrix:
  include:
  - os: linux
    jdk: oraclejdk8
  - os: linux
    jdk: oraclejdk7
  - os: linux
    jdk: openjdk6
  - os: linux
    osx_image: xcode9.3
    language: java
  - os: osx
    jdk: openjdk6
    osx_image: xcode7.3
    language: java
  - os: osx
    osx_image: xcode8
    language: java
  - os: osx
    osx_image: xcode8.3
    language: java
  - os: osx
    osx_image: xcode9
    language: java

install:  "make init"

# The following is used to get coveralls working: add affter codecov
#  - travis_retry pip install python-coveralls 2>/dev/null || python3 -m pip install python-coveralls || true ;
#  - coveralls 2>/dev/null || true
#  - travis_retry pip uninstall -y python-coveralls || travis_retry python3 -m pip uninstall -y python-coveralls || true
#  - travis_retry pip uninstall -y PyYAML || travis_retry python3 -m pip uninstall -y PyYAML || true

script:
  - make clean
  - make test
  - make JavaDoc
  - make clean || exit $?

after_success:
  - echo "DONE."

