version: 2
jobs:
  build:
    working_directory: ~/java-repo
    docker:
      - image: circleci/openjdk:latest
        environment:
          CI: cicleci
          DEBIAN_FRONTEND: noninteractive
          SHELL: /bin/bash
    steps:
      - checkout
      - run:
          shell: /bin/bash
          name: "fetch and pull"
          command: |
            git fetch && git pull --all || true
      - run:
          shell: /bin/bash
          name: "install java coverage attempt"
          command: |
            echo "Not yet implemented" || true
      - run:
          shell: /bin/bash
          name: "clean up for test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "Unit Tests"
          command: |
            make test
      - run:
          shell: /bin/bash
          name: "clean up from test"
          command: |
            make clean
      - run:
          shell: /bin/bash
          name: "check code style and spelling"
          command: |
            make test-style || true
      - run:
          shell: /bin/bash
          name: "clean up when done"
          command: |
            make clean
destination: build
